# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Scripts/release-assets.sh for v0.1.2 — do not edit the copy in dist/.
class Deeptally < Formula
  desc "DeepSeek account balance and rate meter (CLI)"
  homepage "https://github.com/genoma/deeptally"
  version "0.1.2"
  url "https://github.com/genoma/deeptally/releases/download/v0.1.2/deeptally-0.1.2-arm64.tar.gz"
  sha256 "3e3207e320a9994a026f11ec92221f72ac2150dc27601c3dff1c777c0d0a30ad"
  license "GPL-3.0-or-later"

  depends_on arch: :arm64
  depends_on macos: :sequoia

  def install
    libexec.install "deeptally", "DeepTally_DeepTallyCore.bundle"
    # A wrapper, not a symlink: SwiftPM's generated resource accessor looks for the bundle beside the
    # path the process was started with and does not resolve symlinks, so a bin symlink hides the
    # libexec bundle (v0.1.1's formula crashed with a Fatal error because of this).
    (bin/"deeptally").write_env_script libexec/"deeptally", {}
  end

  test do
    assert_match "deeptally", shell_output("#{bin}/deeptally --version")
  end
end
