# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Scripts/release-assets.sh for v0.1.1 — do not edit the copy in dist/.
class Deeptally < Formula
  desc "DeepSeek account balance and rate meter (CLI)"
  homepage "https://github.com/genoma/deeptally"
  version "0.1.1"
  url "https://github.com/genoma/deeptally/releases/download/v0.1.1/deeptally-0.1.1-arm64.tar.gz"
  sha256 "10a4c5f2b14a37095de36334c1593b0abce5a41d1a5c8e91bf33feceaa5111a8"
  license "GPL-3.0-or-later"

  depends_on arch: :arm64
  depends_on macos: :sequoia

  def install
    libexec.install "deeptally", "DeepTally_DeepTallyCore.bundle"
    bin.install_symlink libexec/"deeptally"
  end

  test do
    assert_match "deeptally", shell_output("#{bin}/deeptally --version")
  end
end
